language: minimal
sudo: false

env:
  matrix:
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=master
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - export PATH=${HOME}/.cask/bin:/tmp/emacs/bin:${PATH}
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - emacs --version
  - cask --version

script:
  - make build lint test
